package e2e.renderer.despatchadvice;

import e2e.AbstractTest;
import io.github.project.openubl.xbuilder.content.catalogs.Catalog1;
import io.github.project.openubl.xbuilder.content.catalogs.Catalog18;
import io.github.project.openubl.xbuilder.content.catalogs.Catalog20;
import io.github.project.openubl.xbuilder.content.catalogs.Catalog6;
import io.github.project.openubl.xbuilder.content.models.standard.guia.*;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;

public class DespatchAdviceComplexTest extends AbstractTest {

    @Test
    public void testComplexData() throws Exception {
        // Given
        DespatchAdvice input = DespatchAdvice.builder()
                .serie("T001")
                .numero(100)
                .version("2.1")
                .tipoComprobante(Catalog1.GUIA_REMISION_REMITENTE.getCode())
                .remitente(Remitente.builder()
                        .ruc("12345678912")
                        .razonSocial("Softgreen S.A.C.")
                        .build()
                )
                .destinatario(Destinatario.builder()
                        .tipoDocumentoIdentidad(Catalog6.DNI.getCode())
                        .numeroDocumentoIdentidad("12345678")
                        .nombre("Mi Cliente S.A.C.")
                        .build()
                )
                .comprador(Comprador.builder()
                        .tipoDocumentoIdentidad(Catalog6.DNI.getCode())
                        .numeroDocumentoIdentidad("12345678")
                        .nombre("Mi Cliente S.A.C.")
                        .build()
                )
                .documentoAdicional(DocumentoAdicional.builder()
                        .tipoDocumento("09")
                        .numero("T001-1")
                        .rucEmisor("20100010001")
                        .tipoDocumentoDescripcion("GUIA REMISION")
                        .build()
                )
                .envio(Envio.builder()
                        .tipoTraslado(Catalog20.VENTA.getCode())
                        .pesoTotal(new BigDecimal("100.50"))
                        .pesoTotalUnidadMedida("KGM")
                        .pesoItems(new BigDecimal("90.00"))
                        .sustentoPeso("Empaque madera")
                        .numeroDeBultos(10)
                        .tipoModalidadTraslado(Catalog18.TRANSPORTE_PUBLICO.getCode())
                        .fechaTraslado(dateProvider.now())
                        .chofer(Driver.builder()
                                .tipoDocumentoIdentidad(Catalog6.DNI.getCode())
                                .numeroDocumentoIdentidad("11111111")
                                .nombres("Juan")
                                .apellidos("Perez")
                                .licencia("Q1234567")
                                .tipo("CONDUCTOR_PRINCIPAL")
                                .build())
                        .chofer(Driver.builder()
                                .tipoDocumentoIdentidad(Catalog6.DNI.getCode())
                                .numeroDocumentoIdentidad("22222222")
                                .nombres("Jose")
                                .apellidos("Gomez")
                                .tipo("COPILOTO")
                                .build())
                        .contenedor("CONT-001")
                        .contenedor("CONT-002")
                        .vehiculo(Vehicle.builder()
                                .placa("ABC-123")
                                .numeroCirculacion("TUC-001")
                                .numeroAutorizacion("AUTH-001")
                                .codigoEmisor("MTC")
                                .secundario(Vehicle.builder()
                                        .placa("CAR-456")
                                        .numeroCirculacion("TUC-SEC")
                                        .build()
                                )
                                .build()
                        )
                        .puerto(Puerto.builder()
                                .codigo("CALLAO")
                                .nombre("Puerto del Callao")
                                .build()
                        )
                        .partida(Partida.builder()
                                .direccion("Av. Origen 123")
                                .ubigeo("010101")
                                .codigoLocal("0001")
                                .ruc("12345678912")
                                .build()
                        )
                        .destino(Destino.builder()
                                .direccion("Av. Destino 456")
                                .ubigeo("020202")
                                .codigoLocal("0002")
                                .ruc("87654321098")
                                .build()
                        )
                        .build()
                )
                .detalle(DespatchAdviceItem.builder()
                        .cantidad(new BigDecimal("5.00"))
                        .unidadMedida("NIU")
                        .codigo("ITEM-01")
                        .descripcion("Caja de herramientas")
                        .atributo(GuiaItemAttribute.builder()
                                .name("Color")
                                .code("1001")
                                .value("Rojo")
                                .build()
                        )
                        .atributo(GuiaItemAttribute.builder()
                                .name("Marca")
                                .code("1002")
                                .value("ToolMaster")
                                .build()
                        )
                        .build()
                )
                .build();

        assertInput(input, "complexData.xml");
    }

}
