package pe.gob.sunat.servicio2.registro.electronico.comppago.consulta.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T13:05:40.365-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "billValidService",
                  wsdlLocation = "file:/home/admin/git/sunat-web-services/src/main/resources/wsdl/consulta_factura.wsdl",
                  targetNamespace = "http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/")
public class BillValidService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "billValidService");
    public final static QName BillValidServicePort = new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "BillValidServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/admin/git/sunat-web-services/src/main/resources/wsdl/consulta_factura.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BillValidService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/admin/git/sunat-web-services/src/main/resources/wsdl/consulta_factura.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillValidService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillValidService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillValidService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BillValidService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BillValidService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BillValidService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BillValidService
     */
    @WebEndpoint(name = "BillValidServicePort")
    public pe.gob.sunat.service.BillValidService getBillValidServicePort() {
        return super.getPort(BillValidServicePort, pe.gob.sunat.service.BillValidService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillValidService
     */
    @WebEndpoint(name = "BillValidServicePort")
    public pe.gob.sunat.service.BillValidService getBillValidServicePort(WebServiceFeature... features) {
        return super.getPort(BillValidServicePort, pe.gob.sunat.service.BillValidService.class, features);
    }

}
