package pe.gob.sunat.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T13:05:40.363-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billValidService")
@XmlSeeAlso({ObjectFactory.class})
public interface BillValidService {

    @WebMethod(action = "urn:validaCDPcriterios")
    @Action(input = "urn:validaCDPcriterios", output = "http://service.sunat.gob.pe/billValidService/validaCDPcriteriosResponse")
    @RequestWrapper(localName = "validaCDPcriterios", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ValidaCDPcriterios")
    @ResponseWrapper(localName = "validaCDPcriteriosResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ValidaCDPcriteriosResponse")
    @WebResult(name = "cdpvalidado", targetNamespace = "")
    public pe.gob.sunat.service.StatusResponse validaCDPcriterios(
        @WebParam(name = "rucEmisor", targetNamespace = "")
        java.lang.String rucEmisor,
        @WebParam(name = "tipoCDP", targetNamespace = "")
        java.lang.String tipoCDP,
        @WebParam(name = "serieCDP", targetNamespace = "")
        java.lang.String serieCDP,
        @WebParam(name = "numeroCDP", targetNamespace = "")
        java.lang.String numeroCDP,
        @WebParam(name = "tipoDocIdReceptor", targetNamespace = "")
        java.lang.String tipoDocIdReceptor,
        @WebParam(name = "numeroDocIdReceptor", targetNamespace = "")
        java.lang.String numeroDocIdReceptor,
        @WebParam(name = "fechaEmision", targetNamespace = "")
        java.lang.String fechaEmision,
        @WebParam(name = "importeTotal", targetNamespace = "")
        java.lang.Double importeTotal,
        @WebParam(name = "nroAutorizacion", targetNamespace = "")
        java.lang.String nroAutorizacion
    );

    @WebMethod(action = "urn:verificaCPEarchivo")
    @Action(input = "urn:verificaCPEarchivo", output = "http://service.sunat.gob.pe/billValidService/verificaCPEarchivoResponse")
    @RequestWrapper(localName = "verificaCPEarchivo", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.VerificaCPEarchivo")
    @ResponseWrapper(localName = "verificaCPEarchivoResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.VerificaCPEarchivoResponse")
    @WebResult(name = "archivoverificado", targetNamespace = "")
    public pe.gob.sunat.service.StatusResponse verificaCPEarchivo(
        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre,
        @WebParam(name = "archivo", targetNamespace = "")
        java.lang.String archivo
    );
}
