package pe.gob.sunat.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T13:05:40.585-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billService")
@XmlSeeAlso({ObjectFactory.class})
public interface BillService {

    @WebMethod(action = "urn:sendBill")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendBillResponse")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    public byte[] sendBill(
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        javax.activation.DataHandler contentFile,
        @WebParam(name = "partyType", targetNamespace = "")
        java.lang.String partyType
    );

    @WebMethod(action = "urn:getStatus")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.GetStatusResponse")
    @WebResult(name = "status", targetNamespace = "")
    public pe.gob.sunat.service.StatusResponse getStatus(
        @WebParam(name = "ticket", targetNamespace = "")
        java.lang.String ticket
    );

    @WebMethod(action = "urn:sendSummary")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendSummaryResponse")
    @WebResult(name = "ticket", targetNamespace = "")
    public java.lang.String sendSummary(
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        javax.activation.DataHandler contentFile,
        @WebParam(name = "partyType", targetNamespace = "")
        java.lang.String partyType
    );

    @WebMethod(action = "urn:sendPack")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendPackResponse")
    @WebResult(name = "ticket", targetNamespace = "")
    public java.lang.String sendPack(
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        javax.activation.DataHandler contentFile,
        @WebParam(name = "partyType", targetNamespace = "")
        java.lang.String partyType
    );
}
