/*
 *
 *  * Copyright 2017 Carlosthe19916, Inc. and/or its affiliates
 *  * and other contributors as indicated by the @author tags.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  * http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */

package io.github.carlosthe19916.webservices.utils;

import java.util.Map;
import java.util.TreeMap;

public class SunatErrors {

    private static volatile SunatErrors instance;

    private Map<Integer, String> map = new TreeMap<>();

    private SunatErrors() {
        initializeMap();
    }

    public static SunatErrors getInstance() {
        if (instance == null) {
            synchronized (SunatErrors.class) {
                if (instance == null) {
                    instance = new SunatErrors();
                }
            }
        }
        return instance;
    }

    public String get(int key) {
        return map.get(key);
    }

    public String getWithMaxLength(int key, int maxLength) {
        String message = map.get(key);
        if (message != null) {
            message = message.substring(0, Math.min(message.length(), maxLength));
        }
        return message;
    }

    private void initializeMap() {
        map.put(100, "El sistema no puede responder su solicitud. Intente nuevamente o comuníquese con su Administrador");
        map.put(101, "El encabezado de seguridad es incorrecto");
        map.put(102, "Usuario o contraseña incorrectos");
        map.put(103, "El Usuario ingresado no existe");
        map.put(104, "La Clave ingresada es incorrecta");
        map.put(105, "El Usuario no está activo");
        map.put(106, "El Usuario no es válido");
        map.put(109, "El sistema no puede responder su solicitud. (El servicio de autenticación no está disponible)");
        map.put(110, "No se pudo obtener lainformacióndel tipo de usuario");
        map.put(111, "No tiene el perfil para enviar comprobanteselectrónicos");
        map.put(112, "El usuario debe ser secundario");
        map.put(113, "El usuario noestáafiliado a FacturaElectrónica");
        map.put(125, "No se pudo obtener la constancia");
        map.put(126, "El ticket no le pertenece al usuario");
        map.put(127, "El ticket no existe");
        map.put(130, "El sistema no puede responder su solicitud. (No se pudo obtener el ticket de proceso)");
        map.put(131, "El sistema no puede responder su solicitud. (No se pudo grabar el archivo en el directorio)");
        map.put(132, "El sistema no puede responder su solicitud. (No se pudo grabar escribir en el archivo zip)");
        map.put(133, "El sistema no puede responder su solicitud. (No se pudo grabar la entrada del log)");
        map.put(134, "El sistema no puede responder su solicitud. (No se pudo grabar en el storage)");
        map.put(135, "El sistema no puede responder su solicitud. (No se pudo encolar el pedido)");
        map.put(136, "El sistema no puede responder su solicitud. (No se pudo recibir una respuesta del batch)");
        map.put(137, "El sistema no puede responder su solicitud. (Se obtuvo una respuesta nula)");
        map.put(138, "El sistema no puede responder su solicitud. (Error en Base de Datos)");
        map.put(151, "El nombre del archivo ZIP es incorrecto");
        map.put(152, "No se puede enviar por este método un archivo de resumen");
        map.put(153, "No se puede enviar por este método un archivo por lotes");
        map.put(154, "El RUC del archivo no corresponde al RUC del usuario");
        map.put(155, "El archivo ZIP estavacío");
        map.put(156, "El archivo ZIP esta corrupto");
        map.put(157, "El archivo ZIP no contiene comprobantes");
        map.put(158, "El archivo ZIP contiene demasiados comprobantes para este tipo de envío");
        map.put(159, "El nombre del archivo XML es incorrecto");
        map.put(160, "El archivo XML estavacío");
        map.put(161, "El nombre del archivo XML no coincide con el nombre del archivo ZIP");
        map.put(200, "No se pudo procesar su solicitud. (Ocurrióun error en el batch)");
        map.put(201, "No se pudo procesar su solicitud. (Llego un requerimiento nulo al batch)");
        map.put(202, "No se pudo procesar su solicitud. (No llego información del archivo ZIP)");
        map.put(203, "No se pudo procesar su solicitud. (No seencontróarchivos en lainformacióndel archivo ZIP)");
        map.put(204, "No se pudo procesar su solicitud. (Este tipo de requerimiento solo acepta 1 archivo)");
        map.put(250, "No se pudo procesar su solicitud. (Ocurrióun error desconocido al hacer unzip)");
        map.put(251, "No se pudo procesar su solicitud. (No se pudo crear un directorio para el unzip)");
        map.put(252, "No se pudo procesar su solicitud. (No seencontróarchivos dentro del zip)");
        map.put(253, "No se pudo procesar su solicitud. (No se pudo comprimir la constancia)");
        map.put(300, "No se encontró la raíz documento xml");
        map.put(301, "Elementoraízdel xml noestádefinido");
        map.put(302, "Códigodel tipo de comprobante no registrado");
        map.put(303, "No existe el directorio de schemas");
        map.put(304, "No existe el archivo de schema");
        map.put(305, "El sistema no puede procesar el archivo xml");
        map.put(306, "No se puede leer (parsear) el archivo XML");
        map.put(307, "No se pudo recuperar la constancia");
        map.put(400, "No tiene permiso para enviar casos de pruebas");
        map.put(401, "El caso de prueba no existe");
        map.put(402, "Lanumeracióno nombre del documento ya ha sido enviado anteriormente");
        map.put(403, "El documento afectado por la nota no existe");
        map.put(404, "El documento afectado por la nota se encuentra rechazado");
        map.put(1001, "ID - El dato SERIE-CORRELATIVO no cumple con el formato de acuerdo al tipo de comprobante");
        map.put(1002, "El XML no contieneinformaciónen el tag ID");
        map.put(1003, "InvoiceTypeCode - El valor del tipo de documento es invalido o no coincide con el nombre del archivo");
        map.put(1004, "El XML no contiene el tag o no existeinformaciónde InvoiceTypeCode");
        map.put(1005, "CustomerAssignedAccountID - El dato ingresado no cumple con elestándar");
        map.put(1006, "El XML no contiene el tag o no existeinformaciónde CustomerAssignedAccountID del emisor del documento");
        map.put(1007, "AdditionalAccountID - El dato ingresado no cumple con elestándar");
        map.put(1008, "El XML no contiene el tag o no existeinformaciónde AdditionalAccountID del emisor del documento");
        map.put(1009, "IssueDate - El dato ingresado no cumple con elpatrónYYYY-MM-DD");
        map.put(1010, "El XML no contiene el tag IssueDate");
        map.put(1011, "IssueDate- El dato ingresado no es valido");
        map.put(1012, "ID - El dato ingresado no cumple con elpatrónSERIE-CORRELATIVO");
        map.put(1013, "El XML no contieneinformaciónen el tag ID");
        map.put(1014, "CustomerAssignedAccountID - El dato ingresado no cumple con el estándar");
        map.put(1015, "El XML no contiene el tag o no existeinformaciónde CustomerAssignedAccountID del emisor del documento");
        map.put(1016, "AdditionalAccountID - El dato ingresado no cumple con el estándar");
        map.put(1017, "El XML no contiene el tag AdditionalAccountID del emisor del documento");
        map.put(1018, "IssueDate - El dato ingresado no cumple con elpatrónYYYY-MM-DD");
        map.put(1019, "El XML no contiene el tag IssueDate");
        map.put(1020, "IssueDate- El dato ingresado no es valido");
        map.put(1021, "Error en lavalidaciónde la nota decrédito");
        map.put(1022, "La serie onúmerodel documento modificado por la Nota Electrónica no cumple con el formato establecido");
        map.put(1023, "No se ha especificado el tipo de documento modificado por la Notaelectrónica");
        map.put(1024, "CustomerAssignedAccountID - El dato ingresado no cumple con el estándar");
        map.put(1025, "El XML no contiene el tag o no existeinformaciónde CustomerAssignedAccountID del emisor del documento");
        map.put(1026, "AdditionalAccountID - El dato ingresado no cumple con el estándar");
        map.put(1027, "El XML no contiene el tag AdditionalAccountID del emisor del documento");
        map.put(1028, "IssueDate - El dato ingresado no cumple con elpatrónYYYY-MM-DD");
        map.put(1029, "El XML no contiene el tag IssueDate");
        map.put(1030, "IssueDate- El dato ingresado no es valido");
        map.put(1031, "Error en lavalidaciónde la nota de debito");
        map.put(1032, "El comprobante fue informado previamente en unacomunicaciónde baja");
        map.put(1033, "El comprobante fue registrado previamente con otros datos");
        map.put(1034, "Número de RUC del nombre del archivo no coincide con el consignado en el contenido del archivo XML");
        map.put(1035, "Númerode Serie del nombre del archivo no coincide con el consignado en el contenido del archivo XML");
        map.put(1036, "Número de documento en el nombre del archivo no coincide con el consignado en el contenido del XML");
        map.put(1037, "El XML no contiene el tag o no existeinformaciónde RegistrationName del emisor del documento");
        map.put(1038, "RegistrationName - El nombre orazónsocial del emisor no cumple con elestándar");
        map.put(1039, "Solo se pueden recibir notaselectrónicasque modifican facturas");
        map.put(1040, "El tipo de documento modificado por la notaelectrónicano es valido");
        map.put(1041, "cac:PrepaidPayment/cbc:ID - El tag no contiene el atributo @SchemaID. que indica el tipo de documento que realiza el anticipo");
        map.put(1042, "cac:PrepaidPayment/cbc:InstructionID – El tag no contiene el atributo @SchemaID. Que indica el tipo de documento del emisor del documento del anticipo");
        map.put(1043, "cac:OriginatorDocumentReference/cbc:ID - El tag no contiene el atributo @SchemaID. Que indica el tipo de documento del originador del documento electrónico");
        map.put(1044, "cac:PrepaidPayment/cbc:InstructionID – El dato ingresado no cumple con el estándar");
        map.put(1045, "cac:OriginatorDocumentReference/cbc:ID – El dato ingresado no cumple con el estándar");
        map.put(1046, "cbc:Amount - El dato ingresado no cumple con el estándar");
        map.put(1047, "cbc:Quantity - El dato ingresado no cumple con el estándar");
        map.put(1048, "El XML no contiene el tag o no existe información de PrepaidAmount para un documento con anticipo");
        map.put(1049, "ID - Serie y Número del archivo no coincide con el consignado en el contenido del XML");
        map.put(1050, "El XML no contieneinformaciónen el tag DespatchAdviceTypeCode");
        map.put(1051, "DespatchAdviceTypeCode - El valor del tipo de guía es inválido");
        map.put(1052, "DespatchAdviceTypeCode - No coincide con el consignado en el contenido del XML");
        map.put(1053, "El XML no contieneinformaciónen el tag /DespatchAdvice/cac:OrderReference/cbc:ID");
        map.put(1054, "cac:OrderReference/cac:DocumentReference/cbc:ID - El dato SERIE-número no cumple con el formato de acuerdo a la Guía");
        map.put(1055, "Serie - No cumple con el formato de acuerdo a guía electrónica (EG01 ó TXXXX)");
        map.put(1056, "El XML no contieneinformaciónen el tag /DespatchAdvice/cac:OrderReference/cbc:OrderTypeCode");
        map.put(1057, "El XML no contiene información en el tag cac:AdditionalDocumentReference/cbc:ID");
        map.put(1058, "El XML no contiene información en el tag cac:AdditionalDocumentReference/cbc:DocumentTypeCode");
        map.put(1059, "El XML no contiene firma digital");
        map.put(1060, "El XML no contiene el tag o no existeinformacióndelnúmerode RUC del Remitente");
        map.put(1061, "Elnúmerode RUC del Remitente no existe");
        map.put(1062, "El XML no contiene el tag o no existeinformaciónen el tag /DespatchAdvice/cac:Shipment/cbc:HandlingCode");
        map.put(1063, "cbc:ShippingPriorityLevelCode: El dato ingresado no es valido");
        map.put(1064, "El XML no contiene el tag o no existe información en el tag cac:DespatchLine de bienes a transportar");
        map.put(1065, "El XML no contiene información en el tag cbc:TransportModeCode");
        map.put(1066, "El XML no contiene el tag o no existe información en el tag cac:CarrierParty de datos del transportista");
        map.put(1067, "El XML no contiene el tag o no existe información en el tag cac:TransportMeans de datos delvehículo");
        map.put(1068, "El XML no contiene el tag o no existe información en el tag cac:DriverPerson de datos del conductor");
        map.put(1069, "StartDate: El XML no contiene fecha de inicio de traslado");
        map.put(1070, "StartDate - El dato ingresado no cumple con elpatrónYYYY-MM-DD");
        map.put(1071, "StartDate - El dato ingresado no es valido");
        map.put(1072, "Starttime - El dato ingresado no cumple con elpatrónHH:mm:ss.SZ");
        map.put(1073, "StartTime - El dato ingresado no es valido");
        map.put(1074, "No ha consignado punto de llegada");
        map.put(1075, "No ha consignado punto de partida");
        map.put(2010, "El contribuyente noestáactivo");
        map.put(2011, "El contribuyente noestáhabido");
        map.put(2012, "El contribuyente no está autorizado a emitir comprobantes electrónicos");
        map.put(2013, "El contribuyente no cumple con tipo de empresa o tributos requeridos");
        map.put(2014, "El XML no contiene el tag o no existeinformaciónde CustomerAssignedAccountID del receptor del documento");
        map.put(2015, "El XML no contiene el tag o no existeinformaciónde AdditionalAccountID del receptor del documento");
        map.put(2016, "AdditionalAccountID - El dato ingresado en el tipo de documento de identidad del receptor no cumple con elestándar");
        map.put(2017, "CustomerAssignedAccountID - Elnúmerode documento de identidad delreceptordebe ser RUC");
        map.put(2018, "CustomerAssignedAccountID - El dato ingresado no cumple con el estándar");
        map.put(2019, "El XML no contiene el tag o no existeinformaciónde RegistrationName del emisor del documento");
        map.put(2020, "RegistrationName - El nombre orazónsocial del emisor no cumple con el estándar");
        map.put(2021, "El XML no contiene el tag o no existeinformaciónde RegistrationName del receptor del documento");
        map.put(2022, "RegistrationName - El dato ingresado no cumple con elestándar");
        map.put(2023, "El Numero de orden delítemno cumple con el formato establecido");
        map.put(2024, "El XML no contiene el tag InvoicedQuantity en el detalle de losÍtems");
        map.put(2025, "InvoicedQuantity El dato ingresado no cumple con elestándar");
        map.put(2026, "El XML no contiene el tag cac:Item/cbc:Description en el detalle de losÍtems");
        map.put(2027, "El XML no contiene el tag o no existeinformaciónde cac:Item/cbc:Description del item");
        map.put(2028, "Debe existir el tag cac:AlternativeConditionPrice con un elemento cbc:PriceTypeCode con valor 01");
        map.put(2029, "PriceTypeCode El dato ingresado no cumple con el estándar");
        map.put(2030, "El XML no contiene el tag cbc:PriceTypeCode");
        map.put(2031, "LineExtensionAmount El dato ingresado no cumple con el estándar");
        map.put(2032, "El XML no contiene el tag LineExtensionAmount en el detalle de los Items");
        map.put(2033, "El dato ingresado en TaxAmount de lalíneano cumple con el formato establecido");
        map.put(2034, "TaxAmount es obligatorio");
        map.put(2035, "cac:TaxCategory/cac:TaxScheme/cbc:ID El dato ingresado no cumple con elestándar");
        map.put(2036, "Elcódigodel tributo es invalido");
        map.put(2037, "El XML no contiene el tag cac:TaxCategory/cac:TaxScheme/cbc:ID del Item");
        map.put(2038, "cac:TaxScheme/cbc:Name del item - No existe el tag o el dato ingresado no cumple con elestándar");
        map.put(2039, "El XML no contiene el tag cac:TaxCategory/cac:TaxScheme/cbc:Name del Item");
        map.put(2040, "El tipo deafectacióndel IGV es incorrecto");
        map.put(2041, "El sistema decálculodel ISC es incorrecto");
        map.put(2042, "Debe indicar el IGV. Es un campo obligatorio");
        map.put(2043, "El dato ingresado en PayableAmount no cumple con el formato establecido");
        map.put(2044, "PayableAmount es obligatorio");
        map.put(2045, "El valor ingresado en AdditionalMonetaryTotal/cbc:ID es incorrecto");
        map.put(2046, "AdditionalMonetaryTotal/cbc:ID debe tener valor");
        map.put(2047, "Es obligatorio al menos un AdditionalMonetaryTotal concódigo1001, 1002 o 1003");
        map.put(2048, "El dato ingresado en TaxAmount no cumple con el formato establecido");
        map.put(2049, "TaxAmount es obligatorio");
        map.put(2050, "TaxScheme ID - No existe el tag o el dato ingresado no cumple con elestándar");
        map.put(2051, "Elcódigodel tributo es invalido");
        map.put(2052, "El XML no contiene el tag TaxScheme ID de impuestos globales");
        map.put(2053, "TaxScheme Name - No existe el tag o el dato ingresado no cumple con elestándar");
        map.put(2054, "El XML no contiene el tag TaxScheme Name de impuestos globales");
        map.put(2055, "TaxScheme TaxTypeCode - El dato ingresado no cumple con elestándar");
        map.put(2056, "El XML no contiene el tag TaxScheme TaxTypeCode de impuestos globales");
        map.put(2057, "El Name o TaxTypeCode debe corresponder con el Id para el IGV");
        map.put(2058, "El Name o TaxTypeCode debe corresponder con el Id para el ISC");
        map.put(2059, "El dato ingresado en TaxSubtotal/cbc:TaxAmount no cumple con el formato establecido");
        map.put(2060, "TaxSubtotal/cbc:TaxAmount es obligatorio");
        map.put(2061, "El tag global cac:TaxTotal/cbc:TaxAmount debe tener el mismo valor que cac:TaxTotal/cac:Subtotal/cbc:TaxAmount");
        map.put(2062, "El dato ingresado en PayableAmount no cumple con el formato establecido");
        map.put(2063, "El XML no contiene el tag PayableAmount");
        map.put(2064, "El dato ingresado en ChargeTotalAmount no cumple con el formato establecido");
        map.put(2065, "El dato ingresado enel campo Total Descuentosno cumple con el formato establecido");
        map.put(2066, "Debe indicar unadescripciónpara el tag sac:AdditionalProperty/cbc:Value");
        map.put(2067, "cac:Price/cbc:PriceAmount - El dato ingresado no cumple con elestándar");
        map.put(2068, "El XML no contiene el tag cac:Price/cbc:PriceAmount en el detalle de los Items");
        map.put(2069, "DocumentCurrencyCode - El dato ingresado no cumple con la estructura");
        map.put(2070, "El XML no contiene el tag o no existeinformaciónde DocumentCurrencyCode");
        map.put(2071, "La moneda debe ser la misma en todo el documento");
        map.put(2072, "CustomizationID - La versión del documento no es la correcta");
        map.put(2073, "El XML no contiene el tag o no existeinformaciónde CustomizationID");
        map.put(2074, "UBLVersionID - La versión del UBL no es correcta");
        map.put(2075, "El XML no contiene el tag o no existeinformaciónde UBLVersionID");
        map.put(2076, "cac:Signature/cbc:ID - Falta el identificador de la firma");
        map.put(2077, "El tag cac:Signature/cbc:ID debe contenerinformación");
        map.put(2078, "cac:Signature/cac:SignatoryParty/cac:PartyIdentification/cbc:ID - Debe ser igual al RUC del emisor");
        map.put(2079, "El XML no contiene el tag cac:Signature/cac:SignatoryParty/cac:PartyIdentification/cbc:ID");
        map.put(2080, "cac:Signature/cac:SignatoryParty/cac:PartyName/cbc:Name - No cumple con elestándar");
        map.put(2081, "El XML no contiene el tag cac:Signature/cac:SignatoryParty/cac:PartyName/cbc:Name");
        map.put(2082, "cac:Signature/cac:DigitalSignatureAttachment/cac:ExternalReference/cbc:URI - No cumple con elestándar");
        map.put(2083, "El XML no contiene el tag cac:Signature/cac:DigitalSignatureAttachment/cac:ExternalReference/cbc:URI");
        map.put(2084, "ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/ds:Signature/@Id - No cumple con elestándar");
        map.put(2085, "El XML no contiene el tag ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/ds:Signature/@Id");
        map.put(2086, "ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:CanonicalizationMethod/@Algorithm - No cumple con elestándar");
        map.put(2087, "El XML no contiene el tag ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:CanonicalizationMethod/@Algorithm");
        map.put(2088, "ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:SignatureMethod/@Algorithm - No cumple con elestándar");
        map.put(2089, "El XML no contiene el tag ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:SignatureMethod/@Algorithm");
        map.put(2090, "ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:Reference/@URI - Debe estarvacíopara id");
        map.put(2091, "El XML no contiene el tag ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:Reference/@URI");
        map.put(2092, "ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/.../ds:Transform@Algorithm - No cumple con elestándar");
        map.put(2093, "El XML no contiene el tag ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:Reference/ds:Transform@Algorithm");
        map.put(2094, "ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:Reference/ds:DigestMethod/@Algorithm - No cumple con elestándar");
        map.put(2095, "El XML no contiene el tag ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:Reference/ds:DigestMethod/@Algorithm");
        map.put(2096, "ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:Reference/ds:DigestValue - No cumple con elestándar");
        map.put(2097, "El XML no contiene el tag ext:UBLExtensions/.../ds:Signature/ds:SignedInfo/ds:Reference/ds:DigestValue");
        map.put(2098, "ext:UBLExtensions/.../ds:Signature/ds:SignatureValue - No cumple con elestándar");
        map.put(2099, "El XML no contiene el tag ext:UBLExtensions/.../ds:Signature/ds:SignatureValue");
        map.put(2100, "ext:UBLExtensions/.../ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509Certificate - No cumple con elestándar");
        map.put(2101, "El XML no contiene el tag ext:UBLExtensions/.../ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509Certificate");
        map.put(2102, "Error al procesar la factura");
        map.put(2103, "La serie ingresada no es válida");
        map.put(2104, "Numero de RUC del emisor no existe");
        map.put(2105, "Factura a dar de baja no se encuentra registrada en SUNAT");
        map.put(2106, "Factura a dar de baja ya se encuentra en estado de baja");
        map.put(2107, "Numero de RUC SOL no coincide con RUC emisor");
        map.put(2108, "Presentaciónfuera de fecha");
        map.put(2109, "El comprobante fue registrado previamente con otros datos");
        map.put(2110, "UBLVersionID - La versión del UBL no es correcta");
        map.put(2111, "El XML no contiene el tag o no existeinformaciónde UBLVersionID");
        map.put(2112, "CustomizationID - Laversióndel documento no es correcta");
        map.put(2113, "El XML no contiene el tag o no existeinformaciónde CustomizationID");
        map.put(2114, "DocumentCurrencyCode - El dato ingresado no cumple con la estructura");
        map.put(2115, "El XML no contiene el tag o no existeinformaciónde DocumentCurrencyCode");
        map.put(2116, "El tipo de documento modificado por la Nota decréditodebe ser facturaelectrónicao ticket");
        map.put(2117, "La serie onúmerodel documento modificado por la Nota deCréditono cumple con el formato establecido");
        map.put(2118, "Debe indicar las facturas relacionadas a la Nota deCrédito");
        map.put(2119, "La factura relacionada en la Nota decréditonoestáregistrada.");
        map.put(2120, "La factura relacionada en la nota decréditose encuentra de baja");
        map.put(2121, "La factura relacionada en la nota decréditoestáregistrada como rechazada");
        map.put(2122, "El tag cac:LegalMonetaryTotal/cbc:PayableAmount debe tenerinformaciónvalida");
        map.put(2123, "RegistrationName - El dato ingresado no cumple con elestándar");
        map.put(2124, "El XML no contiene el tag RegistrationName del emisor del documento");
        map.put(2125, "ReferenceID - El dato ingresado debe indicar SERIE-CORRELATIVO del documento al que se relaciona la Nota");
        map.put(2126, "El XML no contieneinformaciónen el tag ReferenceID del documento al que se relaciona la nota");
        map.put(2127, "ResponseCode - El dato ingresado no cumple con la estructura");
        map.put(2128, "El XML no contiene el tag o no existeinformaciónde ResponseCode");
        map.put(2129, "AdditionalAccountID - El dato ingresado en el tipo de documento de identidad del receptor no cumple con elestándar");
        map.put(2130, "El XML no contiene el tag o no existeinformaciónde AdditionalAccountID del receptor del documento");
        map.put(2131, "CustomerAssignedAccountID - El número de documento de identidad del receptor debe ser RUC");
        map.put(2132, "El XML no contiene el tag o no existeinformaciónde CustomerAssignedAccountID del receptor del documento");
        map.put(2133, "RegistrationName - El dato ingresado no cumple con elestándar");
        map.put(2134, "El XML no contiene el tag o no existeinformaciónde RegistrationName del receptor del documento");
        map.put(2135, "cac:DiscrepancyResponse/cbc:Description - El dato ingresado no cumple con la estructura");
        map.put(2136, "El XML no contiene el tag o no existeinformaciónde cac:DiscrepancyResponse/cbc:Description");
        map.put(2137, "El Número de orden delítemno cumple con el formato establecido");
        map.put(2138, "CreditedQuantity/@unitCode - El dato ingresado no cumple con elestándar");
        map.put(2139, "CreditedQuantity - El dato ingresado no cumple con elestándar");
        map.put(2140, "El PriceTypeCode debe tener el valor 01");
        map.put(2141, "cac:TaxCategory/cac:TaxScheme/cbc:ID - El dato ingresado no cumple con elestándar");
        map.put(2142, "Elcódigodel tributo es invalido");
        map.put(2143, "cac:TaxScheme/cbc:Name delítem- No existe el tag o el dato ingresado no cumple con elestándar");
        map.put(2144, "cac:TaxCategory/cac:TaxScheme/cbc:TaxTypeCode El dato ingresado no cumple con elestándar");
        map.put(2145, "El tipo deafectacióndel IGV es incorrecto");
        map.put(2146, "El Nombre Internacional debe ser VAT");
        map.put(2147, "El sistema decálculodel ISC es incorrecto");
        map.put(2148, "El Nombre Internacional debe ser EXC");
        map.put(2149, "El dato ingresado en PayableAmount no cumple con el formato establecido");
        map.put(2150, "El valor ingresado en AdditionalMonetaryTotal/cbc:ID es incorrecto");
        map.put(2151, "AdditionalMonetaryTotal/cbc:ID debe tener valor");
        map.put(2152, "Es obligatorio al menos un AdditionalInformation");
        map.put(2153, "Error al procesar la Nota deCrédito");
        map.put(2154, "TaxAmount - El dato ingresado en impuestos globales no cumple con elestándar");
        map.put(2155, "El XML no contiene el tag TaxAmount de impuestos globales");
        map.put(2156, "TaxScheme ID - El dato ingresado no cumple con elestándar");
        map.put(2157, "Elcódigodel tributo es invalido");
        map.put(2158, "El XML no contiene el tag o no existeinformaciónde TaxScheme ID de impuestos globales");
        map.put(2159, "TaxScheme Name - El dato ingresado no cumple con elestándar");
        map.put(2160, "El XML no contiene el tag o no existeinformaciónde TaxScheme Name de impuestos globales");
        map.put(2161, "CustomizationID - Laversióndel documento no es correcta");
        map.put(2162, "El XML no contiene el tag o no existeinformaciónde CustomizationID");
        map.put(2163, "UBLVersionID - La versión del UBL no es correcta");
        map.put(2164, "El XML no contiene el tag o no existeinformaciónde UBLVersionID");
        map.put(2165, "Error al procesar la Nota de Debito");
        map.put(2166, "RegistrationName - El dato ingresado no cumple con elestándar");
        map.put(2167, "El XML no contiene el tag RegistrationName del emisor del documento");
        map.put(2168, "DocumentCurrencyCode - El dato ingresado no cumple con el formato establecido");
        map.put(2169, "El XML no contiene el tag o no existeinformaciónde DocumentCurrencyCode");
        map.put(2170, "ReferenceID - El dato ingresado debe indicar SERIE-CORRELATIVO del documento al que se relaciona la Nota");
        map.put(2171, "El XML no contieneinformaciónen el tag ReferenceID del documento al que se relaciona la nota");
        map.put(2172, "ResponseCode - El dato ingresado no cumple con la estructura");
        map.put(2173, "El XML no contiene el tag o no existeinformaciónde ResponseCode");
        map.put(2174, "cac:DiscrepancyResponse/cbc:Description - El dato ingresado no cumple con la estructura");
        map.put(2175, "El XML no contiene el tag o no existeinformaciónde cac:DiscrepancyResponse/cbc:Description");
        map.put(2176, "AdditionalAccountID - El dato ingresado en el tipo de documento de identidad del receptor no cumple con elestándar");
        map.put(2177, "El XML no contiene el tag o no existeinformaciónde AdditionalAccountID del receptor del documento");
        map.put(2178, "CustomerAssignedAccountID - Elnúmerode documento de identidad del receptor debe ser RUC.");
        map.put(2179, "El XML no contiene el tag o no existeinformaciónde CustomerAssignedAccountID del receptor del documento");
        map.put(2180, "RegistrationName - El dato ingresado no cumple con elestándar");
        map.put(2181, "El XML no contiene el tag o no existeinformaciónde RegistrationName del receptor del documento");
        map.put(2182, "TaxScheme ID - El dato ingresado no cumple con elestándar");
        map.put(2183, "Elcódigodel tributo es invalido");
        map.put(2184, "El XML no contiene el tag o no existeinformaciónde TaxScheme ID de impuestos globales");
        map.put(2185, "TaxScheme Name - El dato ingresado no cumple con elestándar");
        map.put(2186, "El XML no contiene el tag o no existeinformaciónde TaxScheme Name de impuestos globales");
        map.put(2187, "El Numero de orden delítemno cumple con el formato establecido");
        map.put(2188, "DebitedQuantity/@unitCode El dato ingresado no cumple con elestándar");
        map.put(2189, "DebitedQuantity El dato ingresado no cumple con elestándar");
        map.put(2190, "El XML no contiene el tag Price/cbc:PriceAmount en el detalle de los Items");
        map.put(2191, "El XML no contiene el tag Price/cbc:LineExtensionAmount en el detalle de los Items");
        map.put(2192, "EL PriceTypeCode debe tener el valor 01");
        map.put(2193, "cac:TaxCategory/cac:TaxScheme/cbc:ID El dato ingresado no cumple con elestándar");
        map.put(2194, "Elcódigodel tributo es invalido");
        map.put(2195, "cac:TaxScheme/cbc:Name del item - No existe el tag o el dato ingresado no cumple con elestándar");
        map.put(2196, "cac:TaxCategory/cac:TaxScheme/cbc:TaxTypeCode El dato ingresado no cumple con elestándar");
        map.put(2197, "El tipo deafectacióndel IGV es incorrecto");
        map.put(2198, "El Nombre Internacional debe ser VAT");
        map.put(2199, "El sistema decálculodel ISC es incorrecto");
        map.put(2200, "El Nombre Internacional debe ser EXC");
        map.put(2201, "El tag cac:RequestedMonetaryTotal/cbc:PayableAmount debe tenerinformaciónvalida");
        map.put(2202, "TaxAmount - El dato ingresado en impuestos globales no cumple con el estándar");
        map.put(2203, "El XML no contiene el tag TaxAmount de impuestos globales");
        map.put(2204, "El tipo de documento modificado por la Nota de Debito debe ser facturaelectrónicao ticket");
        map.put(2205, "La serie onúmerodel documento modificado por la Nota de Debito no cumple con el formato establecido");
        map.put(2206, "Debe indicar los documentos afectados por la Nota de Debito");
        map.put(2207, "La factura relacionada en la nota dedébitose encuentra de baja");
        map.put(2208, "La factura relacionada en la nota dedébitoestáregistrada como rechazada");
        map.put(2209, "La factura relacionada en la Nota dedébitonoestáregistrada");
        map.put(2210, "El dato ingresado no cumple con el formato RC-fecha-correlativo");
        map.put(2211, "El XML no contiene el tag ID");
        map.put(2212, "UBLVersionID - La versión del UBL del resumen de boletas no es correcta");
        map.put(2213, "El XML no contiene el tag UBLVersionID");
        map.put(2214, "CustomizationID - La versión del resumen de boletas no es correcta");
        map.put(2215, "El XML no contiene el tag CustomizationID");
        map.put(2216, "CustomerAssignedAccountID - El dato ingresado no cumple con elestándar");
        map.put(2217, "El XML no contiene el tag CustomerAssignedAccountID del emisor del documento");
        map.put(2218, "AdditionalAccountID - El dato ingresado no cumple con elestándar");
        map.put(2219, "El XML no contiene el tag AdditionalAccountID del emisor del documento");
        map.put(2220, "El ID debe coincidir con el nombre del archivo");
        map.put(2221, "El RUC debe coincidir con el RUC del nombre del archivo");
        map.put(2222, "El contribuyente no está autorizado a emitir comprobanteselectrónicos");
        map.put(2223, "El archivo ya fue presentado anteriormente");
        map.put(2224, "Numero de RUC SOL no coincide con RUC emisor");
        map.put(2225, "Numero de RUC del emisor no existe");
        map.put(2226, "El contribuyente noestáactivo");
        map.put(2227, "El contribuyente no cumple con tipo de empresa o tributos requeridos");
        map.put(2228, "RegistrationName - El dato ingresado no cumple con elestándar");
        map.put(2229, "El XML no contiene el tag RegistrationName del emisor del documento");
        map.put(2230, "IssueDate - El dato ingresado no cumple con elpatrónYYYY-MM-DD");
        map.put(2231, "El XML no contiene el tag IssueDate");
        map.put(2232, "IssueDate- El dato ingresado no es valido");
        map.put(2233, "ReferenceDate - El dato ingresado no cumple con elpatrónYYYY-MM-DD");
        map.put(2234, "El XML no contiene el tag ReferenceDate");
        map.put(2235, "ReferenceDate- El dato ingresado no es valido");
        map.put(2236, "La fecha del IssueDate no debe ser mayor al Today");
        map.put(2237, "La fecha del ReferenceDate no debe ser mayor al Today");
        map.put(2238, "LineID - El dato ingresado no cumple con elestándar");
        map.put(2239, "LineID - El dato ingresado debe ser correlativo mayor a cero");
        map.put(2240, "El XML no contiene el tag LineID de SummaryDocumentsLine");
        map.put(2241, "DocumentTypeCode - El valor del tipo de documento es invalido");
        map.put(2242, "El XML no contiene el tag DocumentTypeCode");
        map.put(2243, "El dato ingresado no cumple con elpatrónSERIE");
        map.put(2244, "El XML no contiene el tag DocumentSerialID");
        map.put(2245, "El dato ingresado en StartDocumentNumberID debe sernumérico");
        map.put(2246, "El XML no contiene el tag StartDocumentNumberID");
        map.put(2247, "El dato ingresado en sac:EndDocumentNumberID debe sernumérico");
        map.put(2248, "El XML no contiene el tag sac:EndDocumentNumberID");
        map.put(2249, "Los rangos deben ser mayores a cero");
        map.put(2250, "En el rango de comprobantes, el EndDocumentNumberID debe ser mayor o igual al StartInvoiceNumberID");
        map.put(2251, "El dato ingresado en TotalAmount debe sernuméricomayor o igual a cero");
        map.put(2252, "El XML no contiene el tag TotalAmount");
        map.put(2253, "El dato ingresado en TotalAmount debe sernuméricomayor a cero");
        map.put(2254, "PaidAmount - El dato ingresado no cumple con elestándar");
        map.put(2255, "El XML no contiene el tag PaidAmount");
        map.put(2256, "InstructionID - El dato ingresado no cumple con elestándar");
        map.put(2257, "El XML no contiene el tag InstructionID");
        map.put(2258, "Debe indicar Referencia de Importes asociados a las boletas de venta");
        map.put(2259, "Debe indicar 3 Referencias de Importes asociados a las boletas de venta");
        map.put(2260, "PaidAmount - El dato ingresado debe ser mayor o igual a 0.00");
        map.put(2261, "cbc:Amount - El dato ingresado no cumple con elestándar");
        map.put(2262, "El XML no contiene el tag cbc:Amount");
        map.put(2263, "ChargeIndicator - El dato ingresado no cumple con elestándar");
        map.put(2264, "El XML no contiene el tag ChargeIndicator");
        map.put(2265, "Debe indicar Información acerca del Importe Total de Otros Cargos");
        map.put(2266, "Debe indicar cargos mayores o iguales a cero");
        map.put(2267, "TaxScheme ID - El dato ingresado no cumple con elestándar");
        map.put(2268, "Elcódigodel tributo es invalido");
        map.put(2269, "El XML no contiene el tag TaxScheme ID de Información acerca del importe total de un tipo particular de impuesto");
        map.put(2270, "TaxScheme Name - El dato ingresado no cumple con elestándar");
        map.put(2271, "El XML no contiene el tag TaxScheme Name de impuesto");
        map.put(2272, "TaxScheme TaxTypeCode - El dato ingresado no cumple con elestándar");
        map.put(2273, "TaxAmount - El dato ingresado no cumple con elestándar");
        map.put(2274, "El XML no contiene el tag TaxAmount");
        map.put(2275, "Si elcódigode tributo es 2000, el nombre del tributo debe ser ISC");
        map.put(2276, "Si elcódigode tributo es 1000, el nombre del tributo debe ser IGV");
        map.put(2277, "No se ha consignado ningunainformacióndel importe total de tributos");
        map.put(2278, "Debe indicar Información acerca del importe total de ISC e IGV");
        map.put(2279, "Debe indicar Items de consolidado de documentos");
        map.put(2280, "Existen problemas con lainformacióndel resumen de comprobantes");
        map.put(2281, "Error en lavalidaciónde los rangos de los comprobantes");
        map.put(2282, "Existe documento ya informado anteriormente");
        map.put(2283, "El dato ingresado no cumple con el formato RA-fecha-correlativo");
        map.put(2284, "El XML no contiene el tag ID");
        map.put(2285, "El ID debe coincidir con el nombre del archivo");
        map.put(2286, "El RUC debe coincidir con el RUC del nombre del archivo");
        map.put(2287, "AdditionalAccountID - El dato ingresado no cumple con elestándar");
        map.put(2288, "El XML no contiene el tag AdditionalAccountID del emisor del documento");
        map.put(2289, "CustomerAssignedAccountID - El dato ingresado no cumple con el estándar");
        map.put(2290, "El XML no contiene el tag CustomerAssignedAccountID del emisor del documento");
        map.put(2291, "El contribuyente noestáautorizado a emitir comprobantes electrónicos");
        map.put(2292, "Numero de RUC SOL no coincide con RUC emisor");
        map.put(2293, "Numero de RUC del emisor no existe");
        map.put(2294, "El contribuyente noestáactivo");
        map.put(2295, "El contribuyente no cumple con tipo de empresa o tributos requeridos");
        map.put(2296, "RegistrationName - El dato ingresado no cumple con elestándar");
        map.put(2297, "El XML no contiene el tag RegistrationName del emisor del documento");
        map.put(2298, "IssueDate - El dato ingresado no cumple con elpatrónYYYY-MM-DD");
        map.put(2299, "El XML no contiene el tag IssueDate");
        map.put(2300, "IssueDate - El dato ingresado no es valido");
        map.put(2301, "La fecha del IssueDate no debe ser mayor al Today");
        map.put(2302, "ReferenceDate - El dato ingresado no cumple con elpatrónYYYY-MM-DD");
        map.put(2303, "El XML no contiene el tag ReferenceDate");
        map.put(2304, "ReferenceDate - El dato ingresado no es valido");
        map.put(2305, "LineID - El dato ingresado no cumple con elestándar");
        map.put(2306, "LineID - El dato ingresado debe ser correlativo mayor a cero");
        map.put(2307, "El XML no contiene el tag LineID de VoidedDocumentsLine");
        map.put(2308, "DocumentTypeCode - El valor del tipo de documento es invalido");
        map.put(2309, "El XML no contiene el tag DocumentTypeCode");
        map.put(2310, "El dato ingresado no cumple con elpatrónSERIE");
        map.put(2311, "El XML no contiene el tag DocumentSerialID");
        map.put(2312, "El dato ingresado en DocumentNumberID debe sernuméricoy comomáximode 8dígitos");
        map.put(2313, "El XML no contiene el tag DocumentNumberID");
        map.put(2314, "El dato ingresado en VoidReasonDescription debe contener información válida");
        map.put(2315, "El XML no contiene el tag VoidReasonDescription");
        map.put(2316, "Debe indicar Items en VoidedDocumentsLine");
        map.put(2317, "Error al procesar el resumen de anulados");
        map.put(2318, "CustomizationID - Laversióndel documento no es correcta");
        map.put(2319, "El XML no contiene el tag CustomizationID");
        map.put(2320, "UBLVersionID - Laversióndel UBL no es la correcta");
        map.put(2321, "El XML no contiene el tag UBLVersionID");
        map.put(2322, "Error en lavalidaciónde los rangos");
        map.put(2323, "Existe documento ya informado anteriormente en unacomunicaciónde baja");
        map.put(2324, "El archivo decomunicaciónde baja ya fue presentado anteriormente");
        map.put(2325, "El certificado usado no es el comunicado a SUNAT");
        map.put(2326, "El certificado usado se encuentra de baja");
        map.put(2327, "El certificado usado no se encuentra vigente");
        map.put(2328, "El certificado usado se encuentra revocado");
        map.put(2329, "La fecha deemisiónse encuentra fuera dellímitepermitido");
        map.put(2330, "La fecha de generación de la comunicación debe ser igual a la fecha consignada en el nombre del archivo");
        map.put(2331, "Número de RUC del nombre del archivo no coincide con el consignado en el contenido del archivo XML");
        map.put(2332, "Número de Serie del nombre del archivo no coincide con el consignado en el contenido del archivo XML");
        map.put(2333, "Número de documento en el nombre del archivo no coincide con el consignado en el contenido del XML");
        map.put(2334, "El documento electrónico ingresado ha sido alterado");
        map.put(2335, "El documento electrónico ingresado ha sido alterado");
        map.put(2336, "Ocurrió un error en el proceso de validación de la firma digital");
        map.put(2337, "La moneda debe ser la misma en todo el documento");
        map.put(2338, "La moneda debe ser la misma en todo el documento");
        map.put(2339, "El dato ingresado en PayableAmount no cumple con el formato establecido");
        map.put(2340, "El valor ingresado en AdditionalMonetaryTotal/cbc:ID es incorrecto");
        map.put(2341, "AdditionalMonetaryTotal/cbc:ID debe tener valor");
        map.put(2342, "Fecha deemisiónde la factura no coincide con la informada en lacomunicación");
        map.put(2343, "cac:TaxTotal/cac:TaxSubtotal/cbc:TaxAmount - El dato ingresado no cumple con elestándar");
        map.put(2344, "El XML no contiene el tag cac:TaxTotal/cac:TaxSubtotal/cbc:TaxAmount");
        map.put(2345, "La serie no corresponde al tipo de comprobante");
        map.put(2346, "La fecha de generación del resumen debe ser igual a la fecha consignada en el nombre del archivo");
        map.put(2347, "Los rangos informados en el archivo XML se encuentran duplicados o superpuestos");
        map.put(2348, "Los documentos informados en el archivo XML se encuentran duplicados");
        map.put(2349, "Debe consignar solo un elemento sac:AdditionalMonetaryTotal con cbc:ID igual a 1001");
        map.put(2350, "Debe consignar solo un elemento sac:AdditionalMonetaryTotal con cbc:ID igual a 1002");
        map.put(2351, "Debe consignar solo un elemento sac:AdditionalMonetaryTotal con cbc:ID igual a 1003");
        map.put(2352, "Debe consignar solo un elemento cac:TaxTotal a nivel global para IGV (cbc:ID igual a 1000)");
        map.put(2353, "Debe consignar solo un elemento cac:TaxTotal a nivel global para ISC (cbc:ID igual a 2000)");
        map.put(2354, "Debe consignar solo un elemento cac:TaxTotal a nivel global para Otros (cbc:ID igual a 9999)");
        map.put(2355, "Debe consignar solo un elemento cac:TaxTotal a nivel deítempara IGV (cbc:ID igual a 1000)");
        map.put(2356, "Debe consignar solo un elemento cac:TaxTotal a nivel deítempara ISC (cbc:ID igual a 2000)");
        map.put(2357, "Debe consignar solo un elemento sac:BillingPayment a nivel deítemcon cbc:InstructionID igual a 01");
        map.put(2358, "Debe consignar solo un elemento sac:BillingPayment a nivel deítemcon cbc:InstructionID igual a 02");
        map.put(2359, "Debe consignar solo un elemento sac:BillingPayment a nivel deítemcon cbc:InstructionID igual a 03");
        map.put(2360, "Debe consignar solo un elemento sac:BillingPayment a nivel deítemcon cbc:InstructionID igual a 04");
        map.put(2361, "Debe consignar solo un elemento cac:TaxTotal a nivel deítempara Otros (cbc:ID igual a 9999)");
        map.put(2362, "Debeconsignarsolo un tagcac:AccountingSupplierParty/cbc:AdditionalAccountID");
        map.put(2363, "Debe consignar solo un tag cac:AccountingCustomerParty/cbc:AdditionalAccountID");
        map.put(2364, "El comprobante contiene un tipo y número de Guía de Remisión repetido");
        map.put(2365, "El comprobante contiene un tipo y número de Documento Relacionado repetido");
        map.put(2366, "Elcódigoen el tag sac:AdditionalProperty/cbc:ID debe tener 4 posiciones");
        map.put(2367, "El dato ingresado en PriceAmount del Precio de venta unitario por item no cumple con el formato establecido");
        map.put(2368, "El dato ingresado en TaxSubtotal/cbc:TaxAmount del item no cumple con el formato establecido");
        map.put(2369, "El dato ingresado en PriceAmount del Valor de venta unitario por item no cumple con el formato establecido");
        map.put(2370, "El dato ingresado en LineExtensionAmount del item no cumple con el formato establecido");
        map.put(2371, "El XML no contiene el tag cbc:TaxExemptionReasonCode de Afectacion al IGV");
        map.put(2372, "El tag en el item cac:TaxTotal/cbc:TaxAmount debe tener el mismo valor que cac:TaxTotal/cac:TaxSubtotal/cbc:TaxAmount");
        map.put(2373, "Si existe monto de ISC en el ITEM debe especificar el sistema de cálculo");
        map.put(2374, "La factura a dar de baja tiene una fecha de recepción fuera del plazo permitido");
        map.put(2375, "Fecha de emisión de la boleta no coincide con la fecha de emisión consignada en lacomunicación");
        map.put(2376, "La boleta de venta a dar de baja fue informada en un resumen con fecha derecepciónfuera del plazo permitido");
        map.put(2377, "El Name o TaxTypeCode debe corresponder con el Id para el IGV");
        map.put(2378, "El Name o TaxTypeCode debe corresponder con el Id para el ISC");
        map.put(2379, "Lanumeraciónde boleta de venta a dar de baja fue generada en una fecha fuera del plazo permitido");
        map.put(2380, "El documento tiene observaciones");
        map.put(2381, "Comprobante no cumple con el Grupo 1: No todos losítemscorresponden a operaciones gravadas a IGV");
        map.put(2382, "Comprobante no cumple con el Grupo 2: No todos losítems corresponden a operaciones inafectas o exoneradas al IGV");
        map.put(2383, "Comprobante no cumple con el Grupo 3: Falta leyenda concódigo1002");
        map.put(2384, "Comprobante no cumple con el Grupo 3: Existeítemcon operación onerosa");
        map.put(2385, "Comprobante no cumple con el Grupo 4: DebeexistirTotal descuentos mayor a cero");
        map.put(2386, "Comprobante no cumple con el Grupo 5: Todos losítemsdeben tener operaciones afectas a ISC");
        map.put(2387, "Comprobante no cumple con el Grupo 6: El monto depercepciónno existe o es cero");
        map.put(2388, "Comprobante no cumple con el Grupo 6: Todos losítemsdeben tener código de Afectación al IGV igual a 10");
        map.put(2389, "Comprobante no cumple con el Grupo 7: Elcódigode moneda no es diferente a PEN");
        map.put(2390, "Comprobante no cumple con el Grupo 8: No todos losítemscorresponden a operaciones gravadas a IGV");
        map.put(2391, "Comprobante no cumple con el Grupo 9: No todos losítemscorresponden a operaciones inafectas o exoneradas al IGV");
        map.put(2392, "Comprobante no cumple con el Grupo 10: Falta leyenda concódigo1002");
        map.put(2393, "Comprobante no cumple con el Grupo 10: Existeítemcon operación onerosa");
        map.put(2394, "Comprobante no cumple con el Grupo 11: Debe existir Total descuentos mayor a cero");
        map.put(2395, "Comprobante no cumple con el Grupo 12: Elcódigode moneda no es diferente a PEN");
        map.put(2396, "Si el monto total es mayor a S/. 700.00 debe consignar tipo y numero de documento del adquiriente");
        map.put(2397, "El tipo de documento del adquiriente no puede ser Numero de RUC");
        map.put(2398, "El documento a dar de baja se encuentra rechazado");
        map.put(2399, "El tipo de documento modificado por la Nota decréditodebe ser boletaelectrónica");
        map.put(2400, "El tipo de documento modificado por la Nota dedébitodebe ser boletaelectrónica");
        map.put(2401, "No se puede leer (parsear) el archivo XML");
        map.put(2402, "El caso de prueba no existe");
        map.put(2403, "Lanumeracióno nombre del documento ya ha sido enviado anteriormente");
        map.put(2404, "Documento afectado por la notaelectrónicano se encuentra autorizado");
        map.put(2405, "Contribuyente no se encuentra autorizado como emisor de boletaselectrónicas");
        map.put(2406, "Existemásde un tag sac:AdditionalMonetaryTotal con el mismo ID");
        map.put(2407, "Existemásde un tag sac:AdditionalProperty con el mismo ID");
        map.put(2408, "El dato ingresado en PriceAmount del Valor referencial unitario porítemno cumple con el formato establecido");
        map.put(2409, "Existemásde un tag cac:AlternativeConditionPrice con el mismo cbc:PriceTypeCode");
        map.put(2410, "Se ha consignado un valor invalido en el campo cbc:PriceTypeCode");
        map.put(2411, "Ha consignadomásde un elemento cac:AllowanceCharge con el mismo campo cbc:ChargeIndicator");
        map.put(2412, "Se ha consignadomásde un documento afectado por la nota (tag cac:BillingReference)");
        map.put(2413, "Se ha consignadomásde un motivo o sustento de la nota (tag cac:DiscrepancyResponse/cbc:Description)");
        map.put(2414, "No se ha consignado en la nota el tag cac:DiscrepancyResponse");
        map.put(2415, "Se ha consignado en la notamásde un tag cac:DiscrepancyResponse");
        map.put(2416, "Si existe leyenda Transferida Gratuita debe consignar Total Valor de Venta de Operaciones Gratuitas");
        map.put(2417, "Debe consignar Valor Referencial unitario por ítem en operaciones no onerosas");
        map.put(2418, "Si consigna Valor Referencial unitario por ítem en operaciones no onerosas, la operación debe ser no onerosa");
        map.put(2419, "El dato ingresado en AllowanceTotalAmount no cumple con el formato establecido");
        map.put(2420, "Ya transcurrieronmásde 25díascalendarios para concluir con su proceso dehomologación");
        map.put(2421, "Debe indicar toda lainformaciónde sustento detrasladode bienes");
        map.put(2422, "El valor unitario debe ser menor al precio unitario");
        map.put(2423, "Si ha consignado monto ISC a nivel deítem, debe consignar un monto a nivel de total");
        map.put(2424, "RC Debe consignar solo un elemento sac:BillingPayment a nivel deítemcon cbc:InstructionID igual a 05");
        map.put(2425, "Si laoperaciónes gratuita PriceTypeCode =02 y cbc:PriceAmount> 0 elcódigodeafectaciónde igv debe ser no onerosa es decir diferente de 10,20,30");
        map.put(2426, "Documentos relacionados duplicados en el comprobante");
        map.put(2427, "Solo debe de existir un tag AdditionalInformation");
        map.put(2428, "Comprobante no cumple con grupo de facturas con detracciones");
        map.put(2429, "Comprobante no cumple con grupo de facturas con comercio exterior");
        map.put(2430, "Comprobante no cumple con grupo de facturas con tag de facturaguía");
        map.put(2431, "Comprobante no cumple con grupo de facturas con tags no tributarios");
        map.put(2432, "Comprobante no cumple con grupo de boletas con tags no tributarios");
        map.put(2433, "Comprobante no cumple con grupo de facturas con tag venta itinerante");
        map.put(2434, "Comprobante no cumple con grupo de boletas con tag venta itinerante");
        map.put(2435, "Comprobante no cumple con grupo de boletas con ISC");
        map.put(2436, "Comprobante no cumple con el grupo de boletas de venta conpercepción: El monto depercepciónno existe o es cero");
        map.put(2437, "Comprobante no cumple con el grupo de boletas de venta conpercepción: Todos losítemsdeben tener código de Afectación al IGV igual a 10");
        map.put(2438, "Comprobante no cumple con grupo de facturas con tag venta anticipada I");
        map.put(2439, "Comprobante no cumple con grupo de facturas con tag venta anticipada II");
        map.put(2500, "Ingresar descripción y valor venta por ítem para documento de anticipos");
        map.put(2501, "Valor venta debe ser mayor a cero");
        map.put(2502, "Los valores totales deben ser mayores a cero");
        map.put(2503, "PaidAmount: monto anticipado por documento debe ser mayor a cero");
        map.put(2504, "Falta referencia de la factura relacionada con anticipo");
        map.put(2505, "cac:PrepaidPayment/cbc:ID/@SchemaID: Código de referencia debe ser 02 o 03");
        map.put(2506, "cac:PrepaidPayment/cbc:ID: Factura o boleta no existe o comunicada de Baja");
        map.put(2507, "Factura relacionada con anticipo no corresponde como factura de anticipo");
        map.put(2508, "Ingresar documentos por anticipos");
        map.put(2509, "Total de anticipos diferente a los montos anticipados por documento");
        map.put(2510, "Nro nombre del documento no tiene el formato correcto");
        map.put(2511, "El tipo de documento no es aceptado");
        map.put(2512, "No existe información de serie o número");
        map.put(2513, "Dato no cumple con formato de acuerdo al número de comprobante");
        map.put(2514, "No existe información de receptor de documento");
        map.put(2515, "Dato ingresado no cumple con catalogo 6");
        map.put(2516, "Debe indicar tipo de documento");
        map.put(2517, "Dato no cumple con formato establecido");
        map.put(2518, "Calculo IGV no es correcto");
        map.put(2519, "El importe total no coincide con la sumatoria de los valores de venta mas los tributos mas los cargos");
        map.put(2520, "cac:PrepaidPayment/cbc:InstructionID/@SchemaID – El tipo documento debe ser 6 delcatálogode tipo de documento");
        map.put(2521, "cac:PrepaidPayment/cbc:ID - El dato ingresado debe indicar SERIE-CORRELATIVO del documento que serealizóel anticipo");
        map.put(2522, "No existe información del documento del anticipo.");
        map.put(2523, "GrossWeightMeasure – El dato ingresado no cumple con el formato establecido");
        map.put(2524, "El dato ingresado en Amount no cumple con el formato establecido");
        map.put(2525, "El dato ingresado en Quantity no cumple con el formato establecido");
        map.put(2526, "El dato ingresado en Percent no cumple con el formato establecido");
        map.put(2527, "PrepaidAmount: Monto total anticipado debe ser mayor a cero");
        map.put(2528, "cac:OriginatorDocumentReference/cbc:ID/@SchemaID – El tipo documento debe ser 6 delcatálogode tipo de documento");
        map.put(2529, "RUC queemitiódocumento de anticipo, no existe");
        map.put(2530, "RUC que solicita laemisiónde la factura, no existe");
        map.put(2531, "Códigodel Local Anexo del emisor no existe");
        map.put(2532, "No existe información de modalidad de transporte");
        map.put(2533, "Si ha consignado Transporte Privado, debe consignar Licencia de conducir, Placa, N constancia deinscripcióny marca delvehículo");
        map.put(2534, "Si ha consignado Transporte púbico, debe consignar Datos del transportista");
        map.put(2535, "La nota de crédito por otros conceptos tributarios debe tener Otros Documentos Relacionados");
        map.put(2536, "Serie ynúmerono se encuentra registrado como baja por cambio de destinatario");
        map.put(2537, "cac:OrderReference/cac:DocumentReference/cbc:DocumentTypeCode - El tipo de documento de serie y número dado de baja es incorrecta");
        map.put(2538, "El contribuyente no se encuentra autorizado como emisorelectrónicode Guía o de factura o deboleta FacturaGEM");
        map.put(2539, "El contribuyente noestáactivo");
        map.put(2540, "El contribuyente noestáhabido");
        map.put(2541, "El XML no contiene el tag o no existeinformacióndel tipo de documento identidad del remitente");
        map.put(2542, "cac:DespatchSupplierParty/cbc:CustomerAssignedAccountID@schemeID - El valor ingresado como tipo de documento identidad del remitente es incorrecta");
        map.put(2543, "El XML no contiene el tag o no existeinformaciónde la dirección completa y detallada en domicilio fiscal");
        map.put(2544, "El XML no contiene el tag o no existe información de la provincia en domicilio fiscal");
        map.put(2545, "El XML no contiene el tag o no existe información del departamento en domicilio fiscal");
        map.put(2546, "El XML no contiene el tag o no existe información del distrito en domicilio fiscal");
        map.put(2547, "El XML no contiene el tag o no existe información del país en domicilio fiscal");
        map.put(2548, "El valor del país inválido");
        map.put(2549, "El XML no contiene el tag o no existeinformacióndel tipo de documento identidad del destinatario");
        map.put(2550, "cac:DeliveryCustomerParty/cbc:CustomerAssignedAccountID@schemeID - El dato ingresado de tipo de documento identidad del destinatario no cumple con elestándar");
        map.put(2551, "El XML no contiene el tag o no existeinformaciónde CustomerAssignedAccountID del proveedor de servicios");
        map.put(2552, "El XML no contiene el tag o no existeinformacióndel tipo de documento identidad del proveedor");
        map.put(2553, "cac:SellerSupplierParty/cbc:CustomerAssignedAccountID@schemeID - El dato ingresado no es valido");
        map.put(2554, "Para el motivo de traslado ingresado el Destinatario debe ser igual al remitente");
        map.put(2555, "Destinatario no debe ser igual al remitente");
        map.put(2556, "cbc:TransportModeCode - dato ingresado no es valido");
        map.put(2557, "La fecha del StartDate no debe ser menor al Today");
        map.put(2558, "El XML no contiene el tag o no existeinformaciónen Numero de Ruc del transportista");
        map.put(2559, "/DespatchAdvice/cac:Shipment/cac:ShipmentStage/cac:CarrierParty/cac:PartyIdentification/cbc:ID - El dato ingresado no cumple con el formato establecido");
        map.put(2560, "Transportista no debe ser igual al remitente o destinatario");
        map.put(2561, "El XML no contiene el tag o no existeinformacióndel tipo de documento identidad del transportista");
        map.put(2562, "/DespatchAdvice/cac:Shipment/cac:ShipmentStage/cac:CarrierParty/cac:PartyIdentification/cbc:ID@schemeID - El dato ingresado no es valido");
        map.put(2563, "El XML no contiene el tag o no existeinformaciónde Apellido, Nombre orazónsocial del transportista");
        map.put(2564, "Razónsocial transportista - El dato ingresado no cumple con el formato establecido");
        map.put(2565, "El XML no contiene el tag o no existeinformacióndel tipo de unidad de transporte");
        map.put(2566, "El XML no contiene el tag o no existeinformacióndelNúmerode placa del vehículo");
        map.put(2567, "Númerode placa del vehículo - El dato ingresado no cumple con el formato establecido");
        map.put(2568, "El XML no contiene el tag o no existeinformaciónen el Numero de documento de identidad del conductor");
        map.put(2569, "Documento identidad del conductor - El dato ingresado no cumple con el formato establecido");
        map.put(2570, "El XML no contiene el tag o no existeinformacióndel tipo de documento identidad del conductor");
        map.put(2571, "cac:DriverPerson/ID@schemeID - El valor ingresado de tipo de documento identidad de conductor es incorrecto");
        map.put(2572, "El XML no contiene el tag o no existeinformacióndel Numero de licencia del conductor");
        map.put(2573, "Numero de licencia del conductor - El dato ingresado no cumple con el formato establecido");
        map.put(2574, "El XML no contiene el tag o no existeinformacióndedireccióndetallada de punto de llegada");
        map.put(2575, "El XML no contiene el tag o no existeinformaciónde CityName");
        map.put(2576, "El XML no contiene el tag o no existeinformaciónde District");
        map.put(2577, "El XML no contiene el tag o no existeinformacióndedireccióndetallada de punto de partida");
        map.put(2578, "El XML no contiene el tag o no existeinformaciónde CityName");
        map.put(2579, "El XML no contiene el tag o no existeinformaciónde District");
        map.put(2580, "El XML No contiene el tag o no existe información de la cantidad delítem");
        map.put(2600, "El comprobante fue enviado fuera del plazo permitido.");
        map.put(2601, "Señor contribuyente a la fecha no se encuentra registrado ó habilitado con la condición de Agente de percepción.");
        map.put(2602, "El régimen percepción enviado no corresponde con su condición de Agente de percepción.");
        map.put(2603, "La tasa de percepción enviada no corresponde con el régimen de percepción.");
        map.put(2604, "El Cliente no puede ser el mismo que el Emisor del comprobante de percepción.");
        map.put(2605, "Número de RUC del Cliente no existe.");
        map.put(2606, "Documento de identidad del Cliente no existe.");
        map.put(2607, "La moneda del importe de cobro debe ser la misma que la del documento relacionado.");
        map.put(2608, "Los montos de pago, percibidos y montos cobrados consignados para el documento relacionado no son correctos.");
        map.put(2609, "El comprobante electrónico enviado no se encuentra registrado en la SUNAT.");
        map.put(2610, "La fecha de emisión, Importe total del comprobante y la moneda del comprobante electrónico enviado no son los registrados en los Sistemas de SUNAT.");
        map.put(2611, "El comprobante electrónico no ha sido emitido al cliente.");
        map.put(2612, "La fecha de cobro debe estar entre el primer día calendario del mes al cual corresponde la fecha de emisión del comprobante de percepción o desde la fecha de emisión del comprobante relacionado.");
        map.put(2613, "El Nro. de documento con número de cobro ya se encuentra en la Relación de Documentos Relacionados agregados.");
        map.put(2614, "El Nro. de documento con el número de cobro ya se encuentra registrado como pago realizado.");
        map.put(2615, "Importe total percibido debe ser igual a la suma de los importes percibidos por cada documento relacionado.");
        map.put(2616, "Importe total cobrado debe ser igual a la suma de los importe totales cobrados por cada documento relacionado.");
        map.put(2617, "Señor contribuyente a la fecha no se encuentra registrado ó habilitado con la condición de Agente de retención.");
        map.put(2618, "El régimen retención enviado no corresponde con su condición de Agente de retención.");
        map.put(2619, "La tasa de retención enviada no corresponde con el régimen de retención.");
        map.put(2620, "El Proveedor no puede ser el mismo que el Emisor del comprobante de retención.");
        map.put(2621, "Número de RUC del Proveedor no existe.");
        map.put(2622, "La moneda del importe de pago debe ser la misma que la del documento relacionado.");
        map.put(2623, "Los montos de pago, retenidos y montos pagados consignados para el documento relacionado no son correctos.");
        map.put(2624, "El comprobante electrónico no ha sido emitido por el proveedor.");
        map.put(2625, "La fecha de pago debe estar entre el primer día calendario del mes al cual corresponde la fecha de emisión del comprobante de retención o desde la fecha de emisión del comprobante relacionado.");
        map.put(2626, "El Nro. de documento con el número de pago ya se encuentra en la Relación de Documentos Relacionados agregados.");
        map.put(2627, "El Nro. de documento con el número de pago ya se encuentra registrado como pago realizado.");
        map.put(2628, "Importe total retenido debe ser igual a la suma de los importes retenidos por cada documento relacionado.");
        map.put(2629, "Importe total pagado debe ser igual a la suma de los importes pagados por cada documento relacionado.");
        map.put(2630, "La serie onúmerodel documento(01) modificado por la Nota deCréditono cumple con el formato establecido para tipocódigoNotaCrédito10.");
        map.put(2631, "La serie onúmerodel documento(12) modificado por la Nota deCréditono cumple con el formato establecido para tipocódigoNotaCrédito10.");
        map.put(2632, "La serie onúmerodel documento(56) modificado por la Nota deCréditono cumple con el formato establecido para tipocódigoNotaCrédito10.");
        map.put(2633, "La serie onúmerodel documento(03) modificado por la Nota deCréditono cumple con el formato establecido para tipocódigoNotaCrédito10.");
        map.put(2634, "ReferenceID - El dato ingresado debe indicar serie correcta del documento al que se relaciona la Nota tipo 10.");
        map.put(2635, "Debe existir DocumentTypeCode de Otros documentos relacionados con valor 99 para un tipocódigoNotaCrédito10.");
        map.put(2636, "No existe datos del ID de los documentos relacionados con valor 99 para un tipocódigoNotaCrédito10.");
        map.put(2637, "No existe datos del DocumentType de los documentos relacionados con valor 99 para un tipocódigoNotaCrédito10.");
        map.put(2640, "Operacióngratuita, solo debe consignar un monto referencial");
        map.put(2641, "Operacióngratuita, debe consignar Total valor venta - operaciones gratuitas mayor a cero");
        map.put(2642, "Operaciones deexportación, deben consignar TipoAfectaciónigual a 40");
        map.put(2643, "Factura deoperaciónsujeta IVAP debe consignar Monto de impuestos porítem");
        map.put(2644, "Factura deoperaciónsujeta IVAP solo debe tener ítems con código afectación IGV 17.");
        map.put(2645, "Factura deoperaciónsujeta a IVAP debe consignarítemsconcódigode tributo 1000");
        map.put(2646, "Factura deoperaciónsujeta a IVAP debe consignarítemscon nombre de tributo IVAP");
        map.put(2647, "Código tributo UN/ECE debe ser VAT");
        map.put(2648, "Factura deoperaciónsujeta al IVAP, solo puede consignarinformaciónparaoperacióngravadas");
        map.put(2649, "Operación sujeta al IVAP, debe consignar monto en total operaciones gravadas");
        map.put(2650, "Factura deoperaciónsujeta al IVAP , no debe consignar valor para ISC o debe ser 0");
        map.put(2651, "Factura deoperaciónsujeta al IVAP , no debe consignar valor para IGV o debe ser 0");
        map.put(2652, "Factura deoperaciónsujeta al IVAP , debe registrar mensaje 2007");
        map.put(2653, "Servicios prestados No domiciliados. Total IGV debesermayor a cero");
        map.put(2654, "Servicios prestados No domiciliados. Código tributo a consignar debe ser 1000");
        map.put(2655, "Servicios prestados No domiciliados. El código de afectación debe ser 40");
        map.put(2656, "Servicios prestados No domiciliados. Código tributo UN/ECE debe ser VAT");
        map.put(2657, "El Nro. de documento <serie>-<número> yafueutilizado en laemisiónde CPE.");
        map.put(2658, "El Nro. de documento <serie>-<número> no se hainformadoo no se encuentra en estado Revertido");
        map.put(2659, "La fecha de cobro de cada documento relacionado deben ser del mismo Periodo (mm/aaaa), asimismo estas fechas podrán ser menores o iguales a la fecha de emisión del comprobante de percepción");
        map.put(2660, "Los datos del CPE revertido no corresponden a los registrados en la SUNAT");
        map.put(2661, "La fecha de cobro de cada documento relacionado deben ser del mismo Periodo (mm/aaaa), asimismo estas fechas podrán ser menores o iguales a la fecha de emisión del comprobante deretención");
        map.put(2662, "El Nro. de documento <serie>-<número> yafueutilizado en laemisiónde CRE.");
        map.put(2663, "El documento indicado no existe no puede ser modificado/eliminado");
        map.put(2664, "Elcálculode la base imponible de percepción y el monto de la percepción no coincide con el monto total informado.");
        map.put(2665, "El contribuyente no se encuentra autorizado a emitir Tickets");
        map.put(2666, "Las percepciones son solo válidas para boletas de venta al contado.");
        map.put(2667, "Importe total percibido debe ser igual a la suma de los importes percibidos por cada documento relacionado.");
        map.put(2668, "Importe total cobrado debe ser igual a la suma de los importes cobrados por cada documento relacionado.");
        map.put(2669, "El dato ingresado en TotalInvoiceAmount debe sernuméricomayor a cero");
        map.put(2670, "La razón social no corresponde al ruc informado.");
        map.put(2671, "La fecha de generación de la comunicación debe ser mayor o igual a la fecha de generación del documento revertido.");
        map.put(2672, "La fecha de generación del documento revertido debe ser menor o igual a la fecha actual.");
        map.put(2673, "El dato ingresado no cumple con el formato RR-fecha-correlativo.");
        map.put(2674, "El dato ingresado no cumple con el formato de DocumentSerialID, para DocumentTypeCode con valor 20.");
        map.put(2675, "El dato ingresado no cumple con el formato de DocumentSerialID, para DocumentTypeCode con valor 40.");
        map.put(2676, "El XML no contiene el tag o no existe información del número de RUC del emisor");
        map.put(2677, "El valor ingresado como número de RUC del emisor es incorrecto");
        map.put(2678, "El XML no contiene el atributo o no existe información del tipo de documento del emisor");
        map.put(2679, "El XML no contiene el tag o no existe información del número de documento de identidad del cliente");
        map.put(2680, "El valor ingresado como documento de identidad del cliente es incorrecto");
        map.put(2681, "El XML no contiene el atributo o no existe información del tipo de documento del cliente");
        map.put(2682, "El valor ingresado como tipo de documento del cliente es incorrecto");
        map.put(2683, "El XML no contiene el tag o no existe información del Importe total Percibido");
        map.put(2684, "El XML no contiene el tag o no existe información de la moneda del Importe total Percibido");
        map.put(2685, "El valor de la moneda del Importe total Percibido debe ser PEN");
        map.put(2686, "El XML no contiene el tag o no existe información del Importe total Cobrado");
        map.put(2687, "El dato ingresado en SUNATTotalCashed debe ser numérico mayor a cero");
        map.put(2689, "El XML no contiene el tag o no existe información de la moneda del Importe total Cobrado");
        map.put(2690, "El valor de la moneda del Importe total Cobrado debe ser PEN");
        map.put(2691, "El XML no contiene el tag o no existe información del tipo de documento relacionado");
        map.put(2692, "El tipo de documento relacionado no es válido");
        map.put(2693, "El XML no contiene el tag o no existe información del número de documento relacionado");
        map.put(2694, "Elnúmero de documento relacionado no está permitido o no es valido");
        map.put(2695, "El XML no contiene el tag o no existe información del Importe total documento Relacionado");
        map.put(2696, "El dato ingresado en el importe total documento relacionado debe ser numérico mayor a cero");
        map.put(2697, "El XML no contiene el tag o no existe información del número de cobro");
        map.put(2698, "El dato ingresado en el número de cobro no es válido");
        map.put(2699, "El XML no contiene el tag o no existe información del Importe del cobro");
        map.put(2700, "El dato ingresado en el Importe del cobro debe ser numérico mayor a cero");
        map.put(2701, "El XML no contiene el tag o no existe información de la moneda del documento Relacionado");
        map.put(2702, "El XML no contiene el tag o no existe información de la fecha de cobro del documento Relacionado");
        map.put(2703, "La fecha de cobro del documento relacionado no es válido");
        map.put(2704, "El XML no contiene el tag o no existe informacióndel Importe percibido");
        map.put(2705, "El dato ingresado en el Importe percibido debe ser numérico mayor a cero");
        map.put(2706, "El XML no contiene el tag o no existe información de la moneda de importe percibido");
        map.put(2707, "El valor de la moneda de importe percibido debe ser PEN");
        map.put(2708, "El XML no contiene el tag o no existe información de la Fecha dePercepción");
        map.put(2709, "La fecha depercepciónno es válido");
        map.put(2710, "El XML no contiene el tag o no existe información del Monto total a cobrar");
        map.put(2711, "El dato ingresado en el Monto total a cobrar debe ser numérico mayor a cero");
        map.put(2712, "El XML no contiene el tag o no existe información de la moneda del Monto total a cobrar");
        map.put(2713, "El valor de la moneda del Monto total a cobrar debe ser PEN");
        map.put(2714, "El valor de la moneda de referencia para el tipo de cambio no es válido");
        map.put(2715, "El valor de la moneda objetivo para la Tasa de Cambio debe ser PEN");
        map.put(2716, "El dato ingresado en el tipo de cambio debe ser numérico mayor a cero");
        map.put(2717, "La fecha de cambio no es válido");
        map.put(2718, "El valor de la moneda del documento Relacionado no es válido");
        map.put(2719, "El XML no contiene el tag o no existe información de la moneda de referencia parael tipo de cambio");
        map.put(2720, "El XML no contiene el tag o no existe información de la moneda objetivo para la Tasa de Cambio");
        map.put(2721, "El XML no contiene el tag o no existe información del tipo de cambio");
        map.put(2722, "El XML no contiene el tag o no existe información de la fecha de cambio");
        map.put(2723, "El XML no contiene el tag o no existe información del número de documento de identidad del proveedor");
        map.put(2724, "El valor ingresado como documento de identidad del proveedor es incorrecto");
        map.put(2725, "El XML no contiene el tag o no existe información del Importe total Retenido");
        map.put(2726, "El XML no contiene el tag o no existe información de la moneda del Importe total Retenido");
        map.put(2727, "El XML no contiene el tag o no existe información de la moneda del Importe total Retenido");
        map.put(2728, "El valor de la moneda del Importe total Retenido debe ser PEN");
        map.put(2729, "El XML no contiene el tag o no existe información del Importe total Pagado");
        map.put(2730, "El dato ingresado en SUNATTotalPaid debe ser numérico mayor a cero");
        map.put(2731, "El XML no contiene el tag o no existe información de la moneda del Importe total Pagado");
        map.put(2732, "El valor de la moneda del Importe total Pagado debe ser PEN");
        map.put(2733, "El XML no contiene el tag o no existe información del número de pago");
        map.put(2734, "El dato ingresado en el número de pago no es válido");
        map.put(2735, "El XML no contiene el tag o no existe información del Importe del pago");
        map.put(2736, "El dato ingresado en el Importe del pago debe ser numérico mayor a cero");
        map.put(2737, "El XML no contiene el tag o no existe información de la fecha de pago del documento Relacionado");
        map.put(2738, "La fecha de pago del documento relacionado no es válido");
        map.put(2739, "El XML no contiene el tag o no existe información del Importe retenido");
        map.put(2740, "El dato ingresado en el Importe retenido debe ser numérico mayor a cero");
        map.put(2741, "El XML no contiene el tag o no existe información de la moneda de importe retenido");
        map.put(2742, "El valor de la moneda de importe retenido debe ser PEN");
        map.put(2743, "El XML no contiene el tag o no existe información de la Fecha de Retención");
        map.put(2744, "La fecha de retención no es válido");
        map.put(2745, "El XML no contiene el tag o no existe información del Importe total a pagar (neto)");
        map.put(2746, "El dato ingresado en el Importe total a pagar (neto) debe ser numérico mayor a cero");
        map.put(2747, "El XML no contiene el tag o no existe información de la Moneda del monto neto pagado");
        map.put(2748, "El valor de la Moneda del monto neto pagado debe ser PEN");
        map.put(2749, "La moneda de referencia para el tipo de cambio debe ser la misma que la del documento relacionado");
        map.put(2750, "El comprobante que se informa debe existir y estar en estado emitido");
        map.put(2751, "El comprobante que se informa ya se encuentra en estado revertido");
        map.put(2752, "Elnúmerode ítem no puede estar duplicado");
        map.put(4000, "El documento ya fue presentado anteriormente.");
        map.put(4001, "Elnúmerode RUC del receptor no existe.");
        map.put(4002, "Para el TaxTypeCode,estáusando un valor que no existe en elcatálogo.");
        map.put(4003, "El comprobante fue registrado previamente como rechazado.");
        map.put(4004, "El DocumentTypeCode de lasguíasdebe existir y tener 2 posiciones");
        map.put(4005, "El DocumentTypeCode de lasguíasdebe ser 09 o 31");
        map.put(4006, "El ID de lasguíasdebe tenerinformaciónde la SERIE-NUMERO deguía.");
        map.put(4007, "El XML no contiene el ID de lasguías.");
        map.put(4008, "El DocumentTypeCode de Otros documentos relacionados no cumple con elestándar.");
        map.put(4009, "El DocumentTypeCode de Otros documentos relacionados tiene valores incorrectos.");
        map.put(4010, "El ID de los documentos relacionados no cumplen con elestándar.");
        map.put(4011, "El XML no contiene el tag ID de documentos relacionados.");
        map.put(4012, "El ubigeo indicado en el comprobante no es el mismo queestáregistrado para el contribuyente.");
        map.put(4013, "El RUC del receptor noestáactivo");
        map.put(4014, "El RUC del receptor noestáhabido");
        map.put(4015, "Si el tipo de documento del receptor no es RUC, debe tener operaciones deexportación");
        map.put(4016, "El total valor venta neta de oper. gravadas IGV debe ser mayor a 0.00 o debe existir oper. gravadas onerosas");
        map.put(4017, "El total valor venta neta de oper. inafectas IGV debe ser mayor a 0.00 o debe existir oper. inafectas onerosas o de export.");
        map.put(4018, "El total valor venta neta de oper. exoneradas IGV debe ser mayor a 0.00 o debe existir oper. exoneradas");
        map.put(4019, "Elcálculodel IGV no es correcto");
        map.put(4020, "El ISC noestáinformado correctamente");
        map.put(4021, "Si se utiliza la leyenda concódigo2000, el importe depercepcióndebe ser mayor a 0.00");
        map.put(4022, "Si se utiliza la leyenda con código 2001, el total de operaciones exoneradas debe ser mayor a 0.00");
        map.put(4023, "Si se utiliza la leyenda con código 2002, el total de operaciones exoneradas debe ser mayor a 0.00");
        map.put(4024, "Si se utiliza la leyenda");
    }

}
